# Generated by Django 2.2.1 on 2019-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=128, null=True, verbose_name='作者')),
                ('ISBN', models.CharField(blank=True, max_length=128, null=True, verbose_name='ISBN')),
                ('year', models.CharField(blank=True, max_length=8, null=True, verbose_name='年份')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('language', models.CharField(blank=True, max_length=64, null=True, verbose_name='语言')),
                ('category', models.CharField(blank=True, max_length=64, null=True, verbose_name='分类')),
                ('picture', models.TextField(blank=True, null=True, verbose_name='图片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('download_link_pdf', models.TextField(blank=True, null=True, verbose_name='PDF下载链接')),
                ('download_link_epub', models.TextField(blank=True, null=True, verbose_name='EPUB下载链接')),
                ('price', models.FloatField(verbose_name='价格')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
    ]
