# Generated by Django 2.2.1 on 2019-05-29 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('order_price', models.FloatField(verbose_name='订单金额')),
                ('pay_method', models.IntegerField(choices=[(0, '支付宝'), (1, '微信支付')], verbose_name='支付方式')),
                ('order_pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('order_confirm_time', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '已下单'), (2, '已支付'), (3, '已确认')], default=1, verbose_name='订单状态')),
                ('check_info', models.TextField(blank=True, null=True, verbose_name='发票信息')),
                ('trade_info', models.TextField(blank=True, null=True, verbose_name='交易信息')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='order.Order', verbose_name='订单编号')),
            ],
            options={
                'verbose_name': '交易信息',
                'verbose_name_plural': '交易信息',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(verbose_name='书籍编号')),
                ('book_name', models.CharField(max_length=128, verbose_name='书名')),
                ('book_author', models.CharField(blank=True, max_length=128, null=True, verbose_name='作者')),
                ('book_ISBN', models.CharField(blank=True, max_length=128, null=True, verbose_name='ISBN')),
                ('book_year', models.CharField(blank=True, max_length=8, null=True, verbose_name='年份')),
                ('book_pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('book_language', models.CharField(blank=True, max_length=64, null=True, verbose_name='语言')),
                ('book_category', models.CharField(blank=True, max_length=64, null=True, verbose_name='分类')),
                ('book_picture', models.TextField(blank=True, null=True, verbose_name='图片')),
                ('book_description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('book_download_link_pdf', models.TextField(blank=True, null=True, verbose_name='PDF下载链接')),
                ('book_download_link_epub', models.TextField(blank=True, null=True, verbose_name='EPUB下载链接')),
                ('book_price', models.FloatField(verbose_name='价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='order.Order', verbose_name='订单编号')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
